5th task
htmlacademy-javascript/1605855-kekstagram-22 pull request #6
Opened 2021-02-17 12:13 UTC by gaukharka

2021-02-19 08:33 UTC, ElseeCCD commented on js/user-modal.js
> +    const bigPictureData = pictures.find(photo => photo.id = photoId);
`=` - это оператор присваивания
`==` - это оператор сравнения с приведением типов
`===` - это оператор сравнения без приведения типов

Тебе тут нужен опреатор сравнения. А т.к. использовать оператор сравнения с приведением типов - непредсказуемо, мы всегда используем без приведения, т.е. `===` 

У тебя сейчас при `photo.id === photoId` возвращается undefined из-за того, что id в массиве твоих сгенерированных данных - это число, а card.dataset.id возвращает строку. Т.е. происходит такое сравнение примерно `20 === '20'`, возвращается false, потому что типы данных разные: число и строка. Чтобы было проще, открой data.js и в функции generatePictures, когда создаешь id, создавай там строку:  id: \`${id}\`

2021-02-20 08:05 UTC, ElseeCCD requested changes

2021-02-20 08:05 UTC, ElseeCCD commented on js/user-modal.js
> +    picturePreviewModal.querySelector('.social__caption').textContent = pictures.description;
вынеси все, где получаешь дом-элементы на верх функции-обработчика и переиспользуй потом.

2021-02-20 08:05 UTC, ElseeCCD commented on js/user-modal.js
> +      commentsContainer.querySelector('.social__picture').src = comments.avatar;
нет-нет, тут ты берешь и изменяешь элемент на странице. У тебя там уже может быть какой-то комментарий выведен.
Тебе надо создать сначала элемент, а не получить его из DOMа.
Вот по примеру из демонстраций создавай комментарии: https://up.htmlacademy.ru/javascript/22/demos/4921#13
Создай коробочку, добавь туда все комментарии и отобрази на странице

2021-02-20 21:29 UTC, gaukharka commented on js/user-modal.js
> +  clickHandler(pictureCards[i], pictures[i]);
теперь ругается на evt - undefined. 
![Screenshot 2021-02-20 at 22 27 34](https://user-images.githubusercontent.com/13445239/108608995-0d157f00-73cb-11eb-87eb-001e4ed8b6f2.png)

2021-02-23 08:38 UTC, ElseeCCD requested changes

2021-02-23 08:38 UTC, ElseeCCD commented on js/user-modal.js
> +  socialComments.innerHTML = '';
то же самое написано у тебя двумя строчками выше. Можно же на open очищать просто, а не на close. Или функцию вызвать после определения

2021-02-23 08:38 UTC, ElseeCCD commented on js/user-modal.js
> +//create Comments Section Elements function
а по названию функции, разве, не понятно, что она деалает? Для чего комментарий? Если не понятно, значит надо структуру кода пересмотреть, или, как минимум, название функции сменить

2021-02-23 08:38 UTC, ElseeCCD commented on js/user-modal.js
> +// on photo click handling function
то же самое, если не понятно, что функция делает, значит функция как-то не так названа

2021-02-23 08:38 UTC, ElseeCCD commented on js/user-modal.js
> +  userOpenModal();
я бы сначала все нужные данные подставила бы в модальное окно, а уже потом убирала бы класс hidden

2021-02-23 08:38 UTC, ElseeCCD commented on js/user-modal.js
> +  const comments = picture.comments;
использовала бы деструктуризацию тут:
```
const {url, likes, comments, description} = picture;
bigPictureImg.src = url;
bigPictureLikesCount.textContent = likes;
bigPictureCommentsCount.textContent = comments.length;
bigPictureDescription.textContent = description;
```

2021-02-23 08:38 UTC, ElseeCCD commented on js/user-modal.js
> +const createComment = (tagName, className) => {
ну не комментарий же функция создает. Посмотри внимательно, она принимает на вход любое имя тега и любое имя класса, и возвращает тебе какой-то DOM-элемент, а не комментарий. Утилитарная же функция, в других местах сможешь переиспользовать, вынеси её в свои utils.js, назови так, чтобы соответсвовала тому, что делает: `createElement`. Все функции должны своим названием отображать свою суть, чтобы и тебе самой было удобно код поддерживать, и другим людям

2021-02-23 08:38 UTC, ElseeCCD commented on js/user-modal.js
> +    const commentAvatar = createComment('img', 'social__picture');
странно же выглядит, что ты картинку создаешь функцией createComment, согласись?

2021-02-23 08:38 UTC, ElseeCCD commented on js/user-modal.js
> +    commentText.textContent = comments[j].message;
тут тоже можно всё вынести в начало цикла: `const {avatar, name, message} = comments[j];`

2021-02-23 08:38 UTC, ElseeCCD commented on js/user-modal.js
> +  // });
🤔

2021-02-23 08:38 UTC, ElseeCCD commented on js/user-modal.js
> +  document.addEventListener('keydown', (evt) => {
т.е. если юзер в любой момент нажмет на Enter, мы ему откроем модальное окно? Не важно с какой информацией? А зачем ему это? Вообще, не вижу ничего про Enter в ТЗ и домашке, поэтому, если пока не понимаешь, как это реализовать, отложи

2021-02-23 08:38 UTC, ElseeCCD commented on js/user-modal.js
> +closeButton.forEach((card) => {
и сколько у тебя closeButton на странице? А почему тогда коллекция названа существительным в единственном числе? А почему элемент коллекции closeButton назвается card? А почему слушатель события Esc навешивается при открытии модального окна и удаляется при закрытии, а тут всегда слушает?

2021-02-23 17:47 UTC, ElseeCCD approved these changes

2021-02-23 17:47 UTC, ElseeCCD commented on js/user-modal.js
> +const userCloseModal = () => {
всё отлично, только давай переименуем еще функции в `openModal` и `closeModal`, зачем там какой-то лишний юзер

2021-02-23 17:47 UTC, ElseeCCD commented on js/user-modal.js
> +  evt.preventDefault();
это на самый верх функции перенести надо

2021-02-23 17:47 UTC, merged